version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - '/var/www/docker-conf/nginx/conf.d:/etc/nginx/conf.d'
      - '/var/www/docker-conf/nginx/logs:/var/log/nginx'
      - '/var/www/docker-conf/nginx/html:/usr/share/nginx/html'
