version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    privileged: true
    volumes:
      - '/var/www/docker-config/nginx/conf.d:/etc/nginx/conf.d'
