version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    privileged: true
    volumes:
      - './nginx/conf.d:/etc/nginx/conf.d'
  mysql:
    restart: always
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'Ljp521/*-'
      MYSQL_USER: 'lijiapeng'
      MYSQL_PASS: 'l201314520'
    ports:
      - 3306:3306
