version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    privileged: true
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/www:/etc/www"
      - "/var/www/static:/var/www/static"
  jenkins:
    restart: always
    image: jenkinsci/blueocean
    container_name: jenkins
    ports:
      - 1200:8080
      - 1201:50000
    volumes:
      - "/var/www/jenkins_home:/var/jenkins_home"
      - "./nginx/www:/var/www"
  koa-node:
    image: node:12
    container_name: koa-node
    working_dir: /var/blog_node
    volumes:
      - "/var/www/blog_node:/var/blog_node"
      - "/var/www/static:/var/static"
    ports:
      - 1202:1202
    command: npm run start
  # 主站
  nuxt-project:
    image: node:12
    container_name: nuxt-project
    working_dir: /var/nuxt-project/website
    volumes:
      - "/var/www/nuxt-project:/var/nuxt-project"
    ports:
      - 3000:3000
    command: npm run start
